### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by Teddy12155555** [Rapisurazurite/DiffFace#1]
I really like your work on DiffFace and appreciate the dataset you provided. I have a question regarding the inpainting method: could you provide information about the mask?

**Comment by Rapisurazurite** [comment]
Thanks for raising this issue!

Just to clarify, the mask files are already included within the provided tar file. These masks were randomly selected and combined from the CelebA-HQ dataset.

Please double-check the contents of the tar file, as the masks should be present.

**Comment by Teddy12155555** [comment]
Thanks for the reply! 
After double-checking, I found the mask that you provided—thank you! I also noticed that there are some empty prompts in the JSON files of the "Inpaint" class. Does an empty prompt mean that the image remains unchanged?

**Comment by Rapisurazurite** [comment]
You are correct that some JSON files in the "Inpaint" class have empty prompts. When the prompt is empty, it signifies that the full face mask is being used for inpainting.

We opted for this approach because using specific attribute prompts for full-face editing often resulted in lower-quality images. To avoid this issue and maintain image quality, we utilize the full face mask without a specific prompt and instead incorporate a negative prompt to prevent undesired outcomes.

**Comment by Teddy12155555** [comment]
Sorry for the additional questions. Even if the prompt is empty, the image is still processed by inpainting models. Therefore, should we classify this image as 'Fake' during deepfake detection? 
And could we define this type of image as a 'full face edit' class, for example?

**Comment by Rapisurazurite** [comment]
You are absolutely correct. Every image within the "inpaint" directory is indeed 'Fake'.

**Comment by Teddy12155555** [comment]
Thanks for the explanation!
Here I've visualized two samples, but I think these samples don't match the prompt:

- Edited image still have hair and with opened mouth
<img width="748" alt="截圖 2024-04-30 下午3 05 57" src="https://github.com/Rapisurazurite/DiffFace/assets/43286712/ae6c23a4-67d7-455f-92e6-b242932a19ad">

- There should be some prompts about the eyes and mouth, as the mask pertains to these regions
<img width="747" alt="截圖 2024-04-30 下午3 08 48" src="https://github.com/Rapisurazurite/DiffFace/assets/43286712/7ae07822-c9b9-4853-a5df-0bee0f95a3d2">

**Comment by Rapisurazurite** [comment]
The current inpainting implementation selects a timestep $T$ randomly within the range of $0.2$ to $1$. A value of $T=1$ signifies a fully masked region, necessitating complete regeneration. When $T=0.2$, the diffusion model regenerates the region several times while largely preserving its original appearance. Despite this preservation, these areas are still considered to be manipulated.

**Comment by Teddy12155555** [comment]
Thank you very much for your patient reply!
I'm curious, how can we determine the specific areas of the image that have been manipulated using prompts or semantic masks?

**Comment by Teddy12155555** [comment]
<img width="715" alt="截圖 2024-04-30 下午3 58 55" src="https://github.com/Rapisurazurite/DiffFace/assets/43286712/cccfd3f5-c1f3-4ff5-800f-cb9e8a0e0079">

Here is a clearer example to illustrate the issue. In this image, the semantic masks include the hair, eyes, and mouth, with the prompt describing Mouth Closed, Small Lips, Wavy Hair. However, the final result shows Mouth Closed, Wavy Hair, and Eye Closed, making it challenging to map the actual edited parts and their details in the edited image.

**Comment by Rapisurazurite** [comment]
Actually, both masks and prompts are used in the process. The masked area is randomly assigned a prompt (or possibly none). However, due to the model's randomness, the generated image may not perfectly match the attributes specified in the prompt. Additionally, for attributes not specified by the prompt, the model will generate them randomly.

Therefore, the actual area edited by the model is determined by the mask.

**Comment by Teddy12155555** [comment]
Thank you, I completely understand! 
Will you release the source code for the data generation pipeline in the future? 
Additionally, since you mentioned modifications are based on masks, will the dataset provide information on mask combinations? For example, will the mask be composed of hair, lip, and mouth, so that I can label the modified regions of this image as hair, lip, and mouth?
